### ISSUE TITLE
ビルドエラー

### ISSUE THREAD

**Issue by bigdra50** [Synesthesias/PLATEAU-SDK-for-Unity#134]
このSDKを含めたプロジェクトのビルドができませんでした｡   
エディタでのみ動作する想定のコードがRuntimeで使用されているようです｡

https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/blob/a2bd5c13f158246ad6eea7816221b6fa1bbd8bbf/Runtime/CityImport/AreaSelector/AreaSelectorBehaviour.cs#L185-L205

エラー内容  
```
Library\PackageCache\com.synesthesias.plateau-unity-sdk@1a863b2366\Runtime\CityImport\AreaSelector\AreaSelectorBehaviour.cs(201,17): error CS0103: The name 'EditorUtility' does not exist in the current context
```

```
Library\PackageCache\com.synesthesias.plateau-unity-sdk@1a863b2366\Runtime\CityImport\AreaSelector\AreaSelectorBehaviour.cs(203,13): error CS0103: The name 'EditorUtility' does not exist in the current context
```

https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/blob/a2bd5c13f158246ad6eea7816221b6fa1bbd8bbf/Samples/AttributesSample/Scripts/ClickToShowAttributes.cs#L38  

https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/blob/a2bd5c13f158246ad6eea7816221b6fa1bbd8bbf/Runtime/Util/PathUtil.cs#L156-L162  

エラー内容  

```
Library\PackageCache\com.synesthesias.plateau-unity-sdk@1a863b2366\Samples\AttributesSample\Scripts\ClickToShowAttributes.cs(38,42): error CS0117: 'PathUtil' does not contain a definition for 'SdkPathToAssetPath'
```

開発環境  
- Windows 11
- Unity 2022.3.0
- PLATEAU-SDK-for-Unity v1.1.5

**Comment by linoal** [comment]
ご報告ありがとうございます。お手数をおかけして申し訳ございません。
修正して v1.1.6 を[こちら](https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/releases/tag/v1.1.6)にリリースいたしました。
