### ISSUE TITLE
Rendering Toolkitの自動テクスチャ生成機能を使ったモデルをエクスポートできない問題

### ISSUE THREAD

**Issue by Neuroi014** [Synesthesias/PLATEAU-SDK-for-Unity#215]
Rendering Toolkitの自動テクスチャ生成機能を使ったモデルの修正やエクスポートが出来ません。
モデルの修正に関しては別の形式にした後Blenderなどで修正できますが、そもそもエクスポートが出来ないとゲームの軽量化が出来なくなってしまいます。

本来ゲーム制作などでPLATEAUを使えるようにするためのToolkitsなのにも関わらず、軽量化をする方法が限られているのはあまりよろしくないのではないかと考えました。
個人的に自動テクスチャ生成機能はゲーム制作にとても有効なツールと考えているので、対応のほどお願いできないでしょうか?

**Comment by linoal** [comment]
@Neuroi014 
この度はご意見をくださりありがとうございます。

具体的には次のような症状でございますね：

- Toolkitsの自動テクスチャ生成機能を使ったあと、それをSDKでFBXファイルにエクスポートし、それを再度Unityに取り込みます
- Unityに取り込んだFBXについて、ポリゴンの形状は正しく出ますが、エクスポート前と同じシェーダー、マテリアルプロパティを設定しても元のように窓が光らず、見た目に差異があります

現状、Toolkitsの自動テクスチャ機能はUnityのシーン上の編集に特化しており、FBX等に出力すると必要な情報が失われてしまうため非対応となっております。
見た目を損なわずにシーンファイルを軽量化するための機能について、今後の開発課題とさせて頂きます。

**Comment by Neuroi014** [comment]
テクスチャ自体がうまく表示されず、再設定しても元の状態には戻らないということです。
説明不足で申し訳ありません。

SDK付属のエクスポート機能を利用してエクスポートした場合、テクスチャを再設定した場合でも正しく描画されないことがありました。
(具体的には、天井用のテクスチャが反映されませんでした)

Unity付属のExport To FBXを使用したところ、角度を維持したままエクスポートすることに成功しました。
また、テクスチャを再設定した場合、正しく描画されていることが確認できました。
(あくまで目視上の異常がないということにはなるが)

現時点で判明していることは、エクスポートした時点でテクスチャは崩れるということになります。
(天井に側面のテクスチャが割り当てられていた)

**Comment by tomoki-suzuki-syn** [comment]
@Neuroi014 
お手数をおかけして申し訳ございません。
最新バージョンのv2.3.0では、エクスポートによって天井の代わりに側面が見えるバグが修正されています。

### 詳細：
「天井のテクスチャが出てこず、代わりに側面のテクスチャが見える」という状態から推測するに、3Dモデルの法線が反転しており、天井が裏向きで見えず側面の裏側が見えているものと思われます。
投稿いただいた12月15日の時点では、エクスポートの座標軸が正しくなバグがあり、3Dモデルの法線が反転することがありました。
v2.3.0でエクスポートの座標軸に関する問題を修正いたしました。
大変お手数をおかけしました。

**Comment by Neuroi014** [comment]
詳しいことは不明ですが、SDK付属のエクスポート機能を使用すると、テクスチャのドロップボックスの状態やモデルの出力形式に関わらず、"Default-Material"が付与されています。

また、Unity付属のExport To FBXを使用した場合、モデルに対するマテリアルの付与は適切に行われているものの、マテリアル自体の設定が初期化されています。

環境
Unity 2022.3.12f1
PLATEAU SDK for Unity 2.3.2
Cesium for Unity 1.6.3
PLATEAU SDK Toolkits for Unity 0.2.2
