### ISSUE TITLE
モデルをエクスポートする時、使っていないデフォルトのテクスチャも出力されてしまう

### ISSUE THREAD

**Issue by Neuroi014** [Synesthesias/PLATEAU-SDK-for-Unity#223]
LOD2のオブジェクトをエクスポートする時、実際に使用されているテクスチャ以外にもデフォルトのマテリアルが付与されてしまいます。(Tex_GenericBuildings_top_Diffuseなど)
これにより、エクスポート後のモデルをMesh Bakerでテクスチャを結合すると、このデフォルトのテクスチャも結合されてしまいました。
結合したテクスチャのすべてにデフォルトのテクスチャが含まれているということです。
Blenderなどを使用すれば削除できますが、可能であればエクスポート時のオプションとしてテクスチャを選択しない機能が欲しいです。

**Comment by linoal** [comment]
@Neuroi014 
貴重なご意見をくださりありがとうございます。
エクスポートで「SDK付属のデフォルトテクスチャを含める」かどうかの設定項目を実装しました。
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/1321932/6458cc0d-58fa-4fb3-aac8-7f4e856bf6fc)

開発ブランチの dev/v2 で実装済みで、次回のリリースに含む予定です。
