### ISSUE TITLE
場所による建物のテクスチャのクオリティの違いについての質問

### ISSUE THREAD

**Issue by shingotabuchi** [Synesthesias/PLATEAU-SDK-for-Unity#239]
インポートの設定を変えなくても、場所によって、建物のテクスチャのクオリティが高く見える場所と、そうでない場所があるみたいなのですが、これは元々のデータにクオリティの差があることが原因なのでしょうか？それとも、なんらかの設定によるものなのでしょうか？

新宿（解像度が高いように見える。看板の文字がはっきり読める。）
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/63262819/6777b7e5-9da0-45e4-91bb-126ae5db6e21)
池袋（解像度が低いように見える。看板の内容が読めない。）
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/63262819/0b5caf31-f378-44f9-8d7c-a8121646bc96)
インポート設定
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/63262819/c6148627-9060-434c-a7e8-06fb4243d293)

**Comment by linoal** [comment]
@shingotabuchi 
お問い合わせいただきありがとうございます。
これは元々のデータによるものです。テクスチャの詳細さは現状では都市によって差があります。
インポートの設定によってはテクスチャの詳細さは変化しません。設定項目に「テクスチャ解像度」とありますが、これはテクスチャを結合する粒度を指定するもので、画像の細かさそのものは変化しません。

**Comment by shingotabuchi** [comment]
早速のご返答ありがとうございます。
承知いたしました。
