### ISSUE TITLE
選択範囲を示す青い格子が見えなくなりました

### ISSUE THREAD

**Issue by shingotabuchi** [Synesthesias/PLATEAU-SDK-for-Unity#241]
選択範囲を示す青い格子が見えなくなりました。
PLATEAU SDKのバージョンは2.3.2です。
思い当たる原因などあれば、ご教示いただければ幸いです。
よろしくお願いいたします。
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/63262819/70fa5868-94c2-4ad6-b86b-90d036674722)

**Comment by SYN-miyamoto** [comment]
お問い合わせいただきありがとうございます。
Sceneビューのギズモの設定をオンにしていただくと表示されるかと思います。
ご確認お願いいたします。

**Comment by shingotabuchi** [comment]
ご返信ありがとうございます。
ギズモをオンにしたら表示されました！
ありがとうございました！！

**Comment by SYN-miyamoto** [comment]
良かったです！
また何かありましたらお気軽にお問い合わせください。
