### ISSUE TITLE
テクスチャの重複

### ISSUE THREAD

**Issue by shingotabuchi** [Synesthesias/PLATEAU-SDK-for-Unity#242]
以下の画像の中で選択されている建物は、sljm0370.jpgとsljm037000.jpgという二つの画像を参照していますが、実際の画像を見てみると、この二つの画像は全く同じであるように見えます。
本来１枚の画像で済むところ、同じ画像を複数参照しているのだとしたら、パフォーマンス的によくないと思います。
実際、内容が同じ画像を複数参照しているのでしょうか？
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/63262819/5f2c5c33-40cb-41ec-887d-7e411c56578a)

**Comment by linoal** [comment]
この度は貴重なご意見をくださりありがとうございます。
確認したところ、SDKで読み込むより前の、元データの段階でテクスチャが重複していました。
そこでデータを作っている測量会社に問い合わせたところ、次の返答がありました：

データ出力時もしくは変換時に何らかのエラーがあったのではないかと推察します。そのため、将来的には解消されるかと思います。
作業手順書の中でエラーの例として記載し、データ作成者に注意喚起を促すようにいたします。

**Comment by shingotabuchi** [comment]
ご対応ありがとうございます。
承知いたしました。
