### ISSUE TITLE
メッシュ選択時に青い枠が表示されない

### ISSUE THREAD

**Issue by skeljp** [Synesthesias/PLATEAU-SDK-for-Unity#246]
いつも素晴らしいSDKをありがとうございます。
いままでは問題なくSDKを利用できていたのです,が、突然、インポート時の範囲選択の画面にて、青い枠や選択を意味するオレンジの枠が表示されなくなりました。メッシュの選択自体は効いていて、インポートは可能なのですが、どの範囲を選んでいるのかはわからない状態です。
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/121911587/efe4a479-85dc-49ab-9949-4a410b0e082a)
特にコンソールログもないため原因を探ることもできません。
プロジェクトの再制作、別の市町村のデータでの試行、SDKの再インストール、Unityの再インストールも試しましたが状況は改善しません。
もし何か思い当たる原因がありましたらお知らせいただけると幸いです。

Windows 10 22H2
Unity 2021.3.35f1
Plateau SDK 2.3.2

**Comment by linoal** [comment]
![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/1321932/22a19236-1d73-4cf9-83b1-869558c222af)
ギズモの表示がオフになっているようです。
上図のボタンからギズモをオンにしてみてください。

**Comment by linoal** [comment]
@skeljp 
範囲選択画面でギズモ表示がオフのときに「オンにしてください」と警告を出す機能を開発ブランチに実装しました。次回のリリースに反映される予定です。
操作の疑問点をお寄せいただきありがとうございました。

![image](https://github.com/Synesthesias/PLATEAU-SDK-for-Unity/assets/1321932/04501aca-257b-42e4-ae38-62a5dd873dd6)

**Comment by skeljp** [comment]
なるほど、この青い枠などのUIはギズモ扱いだったのですね。確かにギズモの表紙を切り替えたら青い枠が出てきました！ありがとうございます。初歩的なミスでお恥ずかしい限りです。
また次期バージョンではその点を解決してくださるとのこと、誠にありがとうございます。
