### ISSUE TITLE
ライセンス未定

### ISSUE THREAD

**Issue by linoal** [Synesthesias/PLATEAU-SDK-for-Unity#58]
このSDKのライセンスが正式に決まっていません。  
MIT か Apache-2.0 のどちらになる見込みです。  
ライセンスについて要整理です。

**Comment by Himakuma** [comment]
ライセンスのファイルが、MITで上がっていますが、確定したのでしょうか？

**Comment by linoal** [comment]
@Himakuma 
ライセンスはMITに決まりました。
