### ISSUE TITLE
Importation Problem

### ISSUE THREAD

**Issue by Pasmunt** [Synesthesias/PLATEAU-SDK-for-Unity#68]
I don't know what's wrong with the SDK, I followed everything based on the manual, but there still a lot of errors that's popping out when I'm trying to import a CityGML file. I've attached the Errors below.
Also, may I request a more comprehensive and detailed instruction on How to Import using this SDK, maybe add the required system qualification, GameObjects that needed, scripts, etc. this will a great help for everyone, Thank you.

![image](https://user-images.githubusercontent.com/81037916/214736914-29ec9da1-115f-4f73-bc94-b448eb4b5a54.png)

**Comment by linoal** [comment]
@Pasmunt 
Which one do you use, MacOS or Windows?
If you are using MacOS, we released SDK v1.0.0 that work on MacOS so please use this.
Any version below v1.0.0 not work on MacOS.

Today we added description of supported OS in readme.md.
