### ISSUE TITLE
地図の範囲選択を、シーンを開くのではなく、EditorWindowで操作させてほしい

### ISSUE THREAD

**Issue by Himakuma** [Synesthesias/PLATEAU-SDK-for-Unity#73]
下記のように、EditorWindowで、選択する画面を用意して、
作成中のシーンを閉じないで欲しいです。

https://twitter.com/himakuma_1009/status/1621712658121789440?s=20&t=ippPKLiydDlpyoAFpkQ6_g

**Comment by linoal** [comment]
@Himakuma 
すみません。こちらは実装しないとしてCloseさせてください。

今の実装だと範囲選択画面はシーンビューとゲームオブジェクトに強く依存しています。
地図や枠線表示機能はゲームオブジェクトとして配置され、視界の判定やカメラの移動機能はシーンビューカメラの存在を前提としています。
これを覆し、シーンビューに依存しないようにするにはかなりの工数がかかります。メリットに対して見合わなそうです。
