### ISSUE TITLE
（質問）Git URLでのUPMインポートについて

### ISSUE THREAD

**Issue by drumath2237** [Synesthesias/PLATEAU-SDK-for-Unity#81]
[公式のドキュメント](https://synesthesias.github.io/PLATEAU-SDK-for-Unity/manual/Installation.html#plateau-unity-sdk-%E3%81%AE%E5%B0%8E%E5%85%A5)では、リリースページからtarballをダウンロードしてそれをUPMから指定することで、SDKをインポートするように指示があるかと思います。
個人的にGit URLでのインポートをしたいと考えており、試しに`https://github.com/Synesthesias/PLATEAU-SDK-for-Unity.git#v1.0.0`というURLを指定してSDKをインポートしてみたところ問題なくインポートできたように感じました。

tarballと違いGit URL経由のインポートではダウンロードなどの手間がなくなるというメリットがあり重宝しているのですが、公式ドキュメントで明示されていないということは何か問題があったり、意図していない事などがあるのでしょうか。

**Comment by linoal** [comment]
@drumath2237 
git URL からのインポートでも大丈夫です！
このことを [ドキュメント](https://synesthesias.github.io/PLATEAU-SDK-for-Unity/manual/Installation.html#git%E3%81%AEurl%E6%8C%87%E5%AE%9A%E3%81%A7%E5%B0%8E%E5%85%A5%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95) に記載しました。

**Comment by drumath2237** [comment]
@linoal 
ご回答・ならびにドキュメントへの追記ありがとうございます。承知いたしました！
