### ISSUE TITLE
選択範囲が、画面外に存在している時に、画面内に移動させる機能が欲しい

### ISSUE THREAD

**Issue by Himakuma** [Synesthesias/PLATEAU-SDK-for-Unity#82]
場所を探して、そこに選択範囲を持ってくる時に、
移動させながら持ってこなくてはいけないので、
現在映っている範囲に、選択範囲を、ワンボタン、ダブルクリック等で、持ってくる機能が欲しい

**Comment by linoal** [comment]
貴重なご意見をありがとうございます。
今までの範囲選択UIでは丸い球体を探してドラッグする必要がありましたが、
現在のUIでは直接地図をクリック＆ドラッグで選択できるようになりました。
